server:
  port: 7669
spring:
  application:
    name: provider-8783
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/temp/imgs/

  rabbitmq:
    host: 149.129.118.215
    port: 5672
    username: admin
    password: Zzy123456

eureka:
  client:
    service-url:
      defaultZone: http://server1:7667/eureka/,http://server2:7668/eureka/
img:
  resource-path: D:/temp/imgs/