#端口号
server:
  port: 8889
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: provider1
  rabbitmq:
    host: 149.129.118.215
    port: 5672
    username: admin
    password: Zzy123456

eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8888/eureka/

