server:
  port: 8889
spring:
  application:
    name: provider1
  rabbitmq:
    host: 149.129.118.215
    port: 5672
    username: admin
    password: Zzy123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/