server:
  port: 8783
spring:
  application:
    name: provider-8783
  rabbitmq:
    host: 149.129.118.215
    port: 5672
    username: admin
    password: Zzy123456

eureka:
  client:
    service-url:
      defaultZone: http://server1:8781/eureka/,http://server2:8782/eureka/