server:
  tomcat:
    basedir: C:/filetTmp/img

eurekaservers:
  - ip: localhost
    port: 7667
  - ip: localhost
    port: 7668

async:
  max-pool-size: 80
  core-pool-size: 30
  queue-capacity: 500
  keepalive-seconds: 1200
  allow-core-thread-timeout: true
  thread-name-prefix: 自定义线程池
  rejected-execution-handler: ABORTPOLICY