server:
  port: 8190
spring:
  application:
    name: consumer-8190


eureka:
  client:
    service-url:
      defaultZone: http://server1:8781/eureka/,http://server2:8782/eureka/

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 27000
#ribbon的超时时间
ribbon:
  ReadTimeout: 9000
  ConnectTimeout: 9000

