server:
  tomcat:
    basedir: C:/filetTmp/img

eurekaservers:
  - ip: localhost
    port: 7667
  - ip: localhost
    port: 7668

async:
  max-pool-size: 8
  core-pool-size: 3
  queue-capacity: 50
  keepalive-seconds: 120
  allow-core-thread-timeout: true
  thread-name-prefix: 自定义线程池
  rejected-execution-handler: ABORTPOLICY