server:
  port: 7671

logging:
  config: classpath:log4j2.yml   # 配置log4j2读取的配置文件
  file: ../springlogs/consumer-7671.log

spring:
  application:
    name: consumer-7671
  servlet:
      multipart:
        max-file-size: 100MB    #允许最大文件大小
        max-request-size: 100MB   #单个请求允许最大文件大小
  profiles:
    active: "@profileActive@"   #默认生效的配置文件（dev）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7667/eureka/,http://localhost:7668/eureka/

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 18000
#ribbon的超时时间
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 9000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 9000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
  eureka:
      enabled: true

#feign的熔断机制
feign:
  hystrix:
    enabled: true



