server:
  port: 7671
  servlet:
    context-path: /Consumer-7671
logging:
  config: classpath:log4j2.yml   # 配置log4j2读取的配置文件
  file: ../springlogs/consumer-7671.log

spring:
  application:
    name: consumer-7671
  datasource:
    name:  ${database.name}
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: ${nosql.rabbitmq.host}
    port: ${nosql.rabbitmq.port}
    username: ${nosql.rabbitmq.username}
    password: ${nosql.rabbitmq.password}
  redis:
    database: 3
    host: ${nosql.redis.host}
    port: ${nosql.redis.port}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
  servlet:
    multipart:
      max-file-size: 100MB    #允许最大文件大小
      max-request-size: 100MB   #单个请求允许最大文件大小
  profiles:
    active: "@profileActive@"   #默认生效的配置文件（dev）
  devtools:
    restart:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#mybatis.config-location=classpath:mybatis-config.xml
#mybatis mapper文件的位置
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
#扫描pojo类的位置,在此处指明扫描实体类的包，在mapper中就可以不用写pojo类的全路径名了
  type-aliases-package: com.springcloud.consumerdemo1.mybatis_demo.entity

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${eureka.instance.hostname}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    #  如果项目配置有 server.servlet.context-path 属性，想要被 spring boot admin 监控，就要配置以下属性
    metadata-map:
      user.name: leo
      user.password: zzy12345
      management:
        context-path: ${server.servlet.context-path}/actuator
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eurekaservers[0].ip}:${eurekaservers[0].port}/eureka/,http://${eurekaservers[1].ip}:${eurekaservers[1].port}/eureka/

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
#ribbon的超时时间
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 2500   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2500 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
  eureka:
      enabled: true

#feign的熔断机制
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always