server:
  port: 7671
spring:
  application:
    name: consumer-7671
  rabbitmq:
    host: 149.129.118.215
    port: 5672
    username: admin
    password: Zzy123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7667/eureka/,http://localhost:7668/eureka/

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

#feign的熔断机制
feign:
  hystrix:
    enabled: true



