server:
  tomcat:
    basedir: /root/service/temp/

img:
  resource-path: /root/service/file/

eurekaservers:
  - server:
      ip: localhost
      port: 7667
  - server:
      ip: localhost
      port: 7668