server:
  port: 8000

spring:
  application:
    name: zuul-8000

eureka:
  client:
    service-url:
      defaultZone: http://server1:8781/eureka/,http://server2:8782/eureka/

#由于zuul中的actuator默认的安全权限为ture，需改为false，若不修改则会导致无法访问路由管理（localhost:8000/routes）
#2.x版本写法
management:
  endpoint:
    env:
      enabled: true

#1.x版本写法
#management:
#  security:
#    enabled: false

#zuul超时时间
##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 360000

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 60000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 60000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
  eureka:
    enabled: true

zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 2000
    connect-timeout-millis: 4000