#端口号
server:
  port: 7670
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: provider-7670
  rabbitmq:
    host: 149.129.118.215
    port: 5672
    username: admin
    password: Zzy123456
    publisher-confirms: true
    virtual-host: /

logging:
  config: classpath:log4j2.yml   # 配置log4j2读取的配置文件
  file: ../springlogs/provider-7670.log

eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://server1:8781/eureka/,http://server2:8782/eureka/



